import {
  Ruler,
  Palette,
  Layers,
  Sofa,
  Armchair,
  Bed,
  BedDouble,
  BedSingle,
  Leaf,
  Weight,
  Wind,
  Droplet,
  Flame,
  Blocks,
  Sun,
  Zap,
  Lamp,
  LampDesk,
  LampFloor,
  LampCeiling,
  LampWallUp,
  LampWallDown,
  DoorOpen,
  DoorClosed,
  Table2,
  Loader,
  Feather,
  Star,
  ChevronsUpDown,
  Move3d,
  Bath,
  ShowerHead,
  Blinds,
  Refrigerator,
  Microwave,
  WashingMachine,
  Tv,
  Tv2,
  Monitor,
  CookingPot,
  Utensils,
  ChefHat,
  Coffee,
  Archive,
  Container,
  Shirt,
  Clock,
  Frame,
  Grid3x3,
  type LucideIcon,
} from 'lucide-react';
import {
  MirrorIcon,
  ChandelierIcon,
  PendantLampIcon,
  ToiletIcon,
  SinkIcon,
  RadiatorIcon,
  FireplaceIcon,
  PaintingIcon,
  BarStoolIcon,
  EaselIcon,
  DresserIcon,
  VanityIcon,
  OfficeChairIcon,
  PlantPotIcon,
  CurtainsIcon,
  FanIcon,
  GiftBoxIcon,
  NightstandIcon,
} from './customFurnitureIcons';

export interface AttributeIconDef {
  key: string;
  label: string; // UZ display
  Icon: LucideIcon;
}

// Furniture-focused icon set
export const ATTRIBUTE_ICONS: AttributeIconDef[] = [
  { key: 'ruler', label: "O'lcham", Icon: Ruler },
  { key: 'move3d', label: 'Hajm', Icon: Move3d },
  { key: 'weight', label: 'Og\'irlik', Icon: Weight },
  { key: 'palette', label: 'Rang', Icon: Palette },
  { key: 'layers', label: 'Material', Icon: Layers },
  { key: 'feather', label: 'To\'ldirgich', Icon: Feather },
  { key: 'sofa', label: 'Divan', Icon: Sofa },
  { key: 'armchair', label: 'Kreslo', Icon: Armchair },
  { key: 'bed', label: 'Yotoq', Icon: Bed },
  { key: 'bed-double', label: 'Ikki kishilik krovat', Icon: BedDouble },
  { key: 'bed-single', label: 'Bir kishilik krovat', Icon: BedSingle },
  { key: 'table', label: 'Stol', Icon: Table2 },
  { key: 'door-open', label: 'Ochiq eshik', Icon: DoorOpen },
  { key: 'door-closed', label: 'Yopiq eshik', Icon: DoorClosed },
  { key: 'blocks', label: 'Karkas', Icon: Blocks },
  { key: 'archive', label: 'Komod / Shkaf', Icon: Archive },
  { key: 'container', label: 'Konteyner', Icon: Container },
  { key: 'shirt', label: 'Kiyim shkafi', Icon: Shirt },
  { key: 'frame', label: 'Ramka / Oyna', Icon: Frame },
  { key: 'grid', label: 'Panjara', Icon: Grid3x3 },
  { key: 'clock', label: 'Soat', Icon: Clock },
  { key: 'lamp', label: 'Yorug\'lik', Icon: Lamp },
  { key: 'lamp-desk', label: 'Stol chiroq', Icon: LampDesk },
  { key: 'lamp-floor', label: 'Pol chirog\'i', Icon: LampFloor },
  { key: 'lamp-ceiling', label: 'Shift chirog\'i', Icon: LampCeiling },
  { key: 'lamp-wall-up', label: 'Devor chirog\'i (yuqori)', Icon: LampWallUp },
  { key: 'lamp-wall-down', label: 'Devor chirog\'i (past)', Icon: LampWallDown },
  { key: 'tv', label: 'Televizor', Icon: Tv },
  { key: 'tv2', label: 'TV tumba', Icon: Tv2 },
  { key: 'monitor', label: 'Monitor', Icon: Monitor },
  { key: 'refrigerator', label: 'Muzlatgich', Icon: Refrigerator },
  { key: 'microwave', label: 'Mikroto\'lqinli pech', Icon: Microwave },
  { key: 'washing-machine', label: 'Kir yuvish mashinasi', Icon: WashingMachine },
  { key: 'cooking-pot', label: 'Oshxona', Icon: CookingPot },
  { key: 'utensils', label: 'Idish-tovoq', Icon: Utensils },
  { key: 'chef-hat', label: 'Oshpaz', Icon: ChefHat },
  { key: 'coffee', label: 'Qahva', Icon: Coffee },
  { key: 'bath', label: 'Vanna', Icon: Bath },
  { key: 'shower', label: 'Dush', Icon: ShowerHead },
  { key: 'blinds', label: 'Pardalar', Icon: Blinds },
  { key: 'leaf', label: 'Ekologik', Icon: Leaf },
  { key: 'droplet', label: 'Namlik', Icon: Droplet },
  { key: 'flame', label: 'Yong\'inbardosh', Icon: Flame },
  { key: 'wind', label: 'Nafas oluvchan', Icon: Wind },
  { key: 'sun', label: 'UV himoya', Icon: Sun },
  { key: 'zap', label: 'Elektr', Icon: Zap },
  { key: 'chevrons', label: 'Balandlik', Icon: ChevronsUpDown },
  { key: 'loader', label: 'Yuklama', Icon: Loader },
];

export const ATTRIBUTE_ICON_MAP: Record<string, LucideIcon> = ATTRIBUTE_ICONS.reduce(
  (acc, i) => ({ ...acc, [i.key]: i.Icon }),
  {}
);

export function getAttributeIcon(key: string | undefined | null): LucideIcon {
  if (!key) return Star;
  return ATTRIBUTE_ICON_MAP[key] || Star;
}
